import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="sprayingtoolkit",
    version="0.0.1",
    author="Foo Bar (@byt3bl33d3r)",
    author_email="foo@bar.org",
    description="Password spraying toolkit targetting Lync, Skype for Business and Outlook Web Access",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://gitlab.com/byt3bl33d3r/SprayingToolkit",
    packages=setuptools.find_packages(),
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Information Technology',
        'Intended Audience :: System Administrators',
        'Topic :: Security',
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
    ],
    python_requires='>=3.6',
    install_requires=[
        'PrettyTable',
        'asn1crypto==0.24.0',
        'blinker==1.4',
        'boto3==1.9.210',
        'botocore==1.12.210',
        'brotlipy==0.7.0',
        'certifi==2019.6.16',
        'cffi==1.12.3',
        'chardet==3.0.4',
        'click==6.7',
        'cryptography==2.3.1',
        'docopt==0.6.2',
        'docutils==0.15.2',
        'h11==0.7.0',
        'h2==3.1.1',
        'hpack==3.0.0',
        'hyperframe==5.2.0',
        'idna==2.8',
        'imapclient==2.1.0',
        'jmespath==0.9.4',
        'kaitaistruct==0.8',
        'ldap3==2.5.2',
        'lxml==4.4.1',
        'mitmproxy==4.0.4',
        'ntlm-auth==1.3.0',
        'passlib==1.7.1',
        'pyasn1==0.4.6',
        'pycparser==2.19',
        'pyopenssl==18.0.0',
        'pyparsing==2.2.2',
        'pyperclip==1.6.5',
        'requests-ntlm==1.1.0',
        'requests==2.22.0',
        'ruamel.yaml==0.15.100',
        's3transfer==0.2.1',
        'six==1.12.0',
        'sortedcontainers==2.0.5',
        'termcolor==1.1.0',
        'tornado==5.1.1',
        'urllib3==1.25.3',
        'urwid==2.0.1',
        'wsproto==0.11.0',
    ],
    entry_points={
        'console_scripts': [
            'atomizer=sprayingtoolkit.atomizer:main',
            'spindrift=sprayingtoolkit.spindrift:main',
        ],
    },
    project_urls={  # Optional
        'Bug Reports': 'https://github.com/byt3bl33d3r/SprayingToolkit/issues',
        'Source': 'https://github.com/byt3bl33d3r/SprayingToolkit/',
    },
)
